### ISSUE TITLE
Deploying to AWS EKS

### ISSUE THREAD

**Issue by mosesliao** [karol-brejna-i/locust-experiments#15]
Hi. Any tips to deploy this to EKS?

**Comment by karol-brejna-i** [comment]
Sorry, I never used AWS EKS. I suspect you interact with the service as with any Kubernetes cluster.

From what I see (https://docs.aws.amazon.com/eks/latest/userguide/what-is-eks.html), after creating EKS cluster, you can configure tools like `kubectl` and you are good to go. They write: "Deploy and manage applications on your Amazon EKS cluster the same way that you would with any other Kubernetes environment."

"Proper" way of deploying Locust on K8s would probably be using helm charts (or sth. similar).

Good luck!

**Comment by mosesliao** [comment]
Since you did not close the issue I recycle it.

https://github.com/karol-brejna-i/locust-experiments/blob/master/kubernetes/scripts-cm.yaml#L5.

I have a separate locustfile.py and I don't want to do the way you do because it is pretty big. Is there a way to copy the file into the volume instead in the YML file?

**Comment by karol-brejna-i** [comment]
Please, take a look at locust-slave-deployment.yaml:
* https://github.com/karol-brejna-i/locust-experiments/blob/master/kafka-client/kubernetes/locust/locust-slave-deployment.yaml#L49-L51
* https://github.com/karol-brejna-i/locust-experiments/blob/master/kafka-client/kubernetes/locust/locust-slave-deployment.yaml#L57-L60

Actually, the config map is mounted as a volume. 
You could mount a "normal" volume here -- not a config map.
You would put your locust files there.

There are probably good sources on how to do that on EKS (https://containerjournal.com/topics/container-networking/using-ebs-and-efs-as-persistent-volume-in-kubernetes/).

Good luck!

Now I am closing this issue ;-)

**Comment by karol-brejna-i** [comment]
@liaogz82 Additional thing. If your locustfile is big it is probably using some external references. There are several ways to deal with that (include them). The simplest one for me is building your own docker image with the required libraries installed like here: https://github.com/karol-brejna-i/locust-experiments/blob/master/sending-results/Dockerfile
