### ISSUE TITLE
Helm Chart

### ISSUE THREAD

**Issue by rahulraju93** [karol-brejna-i/locust-experiments#9]
Hello Karol,
                  Great job with this. I am using it to test other metrics such as CPU as well. How can I modify the scripts to engage the CPU and Disk as well?

**Comment by karol-brejna-i** [comment]
@rahulraju93, sorry for the late response (there were holidays here).
Could you, please, elaborate. I don't think I understood what you are trying to achieve.

**Comment by karol-brejna-i** [comment]
Trying to guess what you asking about:

The "standard" setup of load testing would look something like this one: 
![locust metrics](https://user-images.githubusercontent.com/10846210/38305240-774cb56c-380c-11e8-96df-7fe4ddc6d0b4.png)

You have dedicated nodes for Locust and there is service/system under testing on some other nodes. 
The system nodes are monitored (colectd, https://snap-telemetry.io/, whatever) for CPU, MEM, disk (etc.) metrics.
Then you'd probably had some forwarder that would put the metrics into some data store.
Having locust results also sent there would allow you for data correlation (ask questions like: how CPU behaved when the load was high, etc.)

I was planning to demonstrate sending results to a dedicated store. Maybe this info would be useful.
